nuke.pluginAddPath('T:/dwtv/mmo/Nuke_MMO/Compositing/Published/Gizmos')
nuke.pluginAddPath('T:/dwtv/mmo/Nuke_MMO/Compositing/Published/Gizmos/ARCHIVE')
nuke.pluginAddPath('T:/dwtv/mmo/Nuke_MMO/Compositing/Published/Gizmos/Characters')
nuke.pluginAddPath('T:/dwtv/mmo/Nuke_MMO/Compositing/Published/Gizmos/Comp')
nuke.pluginAddPath('T:/dwtv/mmo/Nuke_MMO/Compositing/Published/Gizmos/Props')
nuke.pluginAddPath('T:/dwtv/mmo/Nuke_MMO/Compositing/Published/Gizmos/Sets')
